[tool.poetry]
name = "sentry-auth-oidc"
version = "6.0.0"
description = "OpenID Connect authentication provider for Sentry"
authors = ["Max Wittig <max.wittig@siemens.com>"]
license = "Apache 2.0"
readme = "README.rst"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
]
packages = [
    { include = "oidc" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
isort = "^5.11.4"
flake8 = "^5.0.4"
codecov = "^2.1.12"
pytest = "^7.2.1"

[tool.isort]
profile = "black"

[tool.poetry.plugins."sentry.apps"]
"oidc" = "oidc.apps.Config"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
