name: Publish

on:
  push:
    tags:
      - '*'

env:
  PY_COLORS: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: abatilo/actions-poetry@v2.3.0
      - name: Publish package
        run: |
          poetry install -n --no-dev
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_SECRET }}
